config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'tasks#index', as: :authenticated_root
      resources :tasks do
        member do
          post :next_status
          post :revert_status
        end
      end
      resources :sub_tasks do
        member do
          post :next_status
          post :revert_status
        end
      end
      resources :messages
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :statusable, polymorphic: true
end

app/models/sub_task.rb
class SubTask < ApplicationRecord
  belongs_to :tasks, optional: true
  has_many :status, as: :statusable

  after_create :set_initial_status
  before_destroy :check_status
  after_destroy :delete_status

  private
  def set_initial_status
    status.create(display: "Pending")
  end

  def check_status
    status.count <= 1
  end

  def delete_status
    status.destroy_all   
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :status, as: :statusable
  has_many :sub_tasks
  accepts_nested_attributes_for :sub_tasks, reject_if: proc { |attributes| attributes['description'].blank? }

  after_create :set_initial_status

  private
  def set_initial_status
    status.create(display: "Pending")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, -> { order(created_at: :DESC)}
  has_many :messages

  after_create :send_welcome_mail

  private

  def send_welcome_mail
    WelcomeEmailJob.set(wait: 2.minutes).perform_later(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include ApplicationHelper
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def create
    message = current_user.messages.create!(message_params)
    if message.save
      ActionCable.server.broadcast 'room_channel',
                          body: message.body
    end

  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController
  before_action :set_sub_task

  def destroy
    respond_to do |format|
      format.html { redirect_to authenticated_root_path,
                    notice: "Failed to delete Sub Task." } and return if
                    !@sub_task.destroy
      format.html { redirect_to authenticated_root_path, notice: "Task was successfully deleted." }
    end
  end

  def next_status
    respond_to do |format|
      format.html { redirect_to authenticated_root_path,
                    notice: "Failed to update Sub Task status." } and return if
                    !update_next_status(@sub_task)
      format.html { redirect_to authenticated_root_path, notice: "Task status updated." }
    end
  end

  def revert_status
    respond_to do |format|
      format.html { redirect_to authenticated_root_path,
                    notice: "Failed to update Sub Task status." } and return if
                    !update_previous_status(@sub_task)
      format.html { redirect_to authenticated_root_path, notice: "Task status updated." }
    end
  end

  private
  def set_sub_task
    @sub_task = SubTask.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]
  def index
    @pagy, @tasks = pagy(current_user.tasks.all.includes(
                          :status,
                          sub_tasks: [
                            :status
                          ]),
                        items: 10)
  end

  def create
    respond_to do |format|
      format.html { redirect_to authenticated_root_path,
                    notice: "Failed to create Task." } and return if
                    !current_user.tasks.create!(task_params)
      format.html { redirect_to authenticated_root_path, notice: "Task was successfully created." }
    end
  end

  def edit
    render json: @task.sub_tasks
  end

  def update
    respond_to do |format|
      format.html { redirect_to authenticated_root_path,
                    notice: "Failed to update Task." } and return if
                    !@task.update!(task_params)
      format.html { redirect_to authenticated_root_path, notice: "Task was successfully updated." }
    end
  end

  def destroy
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, sub_tasks_attributes: [:description, :id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def update_next_status(model)
    res = false
    display = model.status.last.display
    if display == "Pending"
      res = model.status.create(display: "Ongoing")
    elsif display == "Ongoing"
      res = model.status.create(display: "Done")
    end
    res
  end

  def update_previous_status(model)
    res = false
    display = model.status.last.display
    if display == "Ongoing"
      res = model.status.create(display: "Pending")
    elsif display == "Done"
      res = model.status.create(display: "Ongoing")
    end
    res
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sub_tasks_helper.rb
module SubTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Tasks</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Messages", messages_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to current_user.email.split('@')[0], destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link', :data => {:confirm => 'Are you sure?'} %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if controller_name != 'sessions' && controller_name != 'registrations' %>
      <%= render 'layouts/header' %>
    <% end %>
    <div class="container pt-5">
      <div class="row d-flex justify-content-center">
        <div class="col-6">
            <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <p><%= message.body %></p>
</div>

app/views/messages/index.html.erb
<h1>Chat room</h1>

<div id="messages" style="height: 400px; overflow-y: scroll">
  <%= render @messages %>
</div>

<%= form_with url: messages_path, method: :post do |form| %>
  <label>Say something:</label><br>
  <%= form.text_field :body, id: 'message', name: "message[body]" %>
  <%= form.submit "Send", data: { disable_with: false } %>
<% end %>

app/views/tasks/index.html.erb
<% if !@tasks.empty? %>
  <%= link_to 'Create new', '#', class: "btn btn-primary btn-sm mb-3", data: { toggle: "modal", target: "#task_modal" } %>
  <div class="accordion" id="tasks_accordion">
    <div class="card">
        <% @tasks.each do |task| %>
          <%= render partial: 'tasks/partials/task_item',
              locals: { task: task, sub_tasks: task.sub_tasks } %>
        <% end %>
    </div>
  </div>
  <div class="d-flex justify-content-end mt-3">
    <%== pagy_bootstrap_nav(@pagy)%>
  </div>
<% else %>
  <div class="alert alert-secondary text-center" role="alert">
    No Tasks yet, <%= link_to "Create now", new_task_path, data: {toggle: "modal", target: "#task_modal"} %>.
  </div>
<% end %>



<%= render 'tasks/partials/modal' %>

app/views/tasks/partials/_modal.html.erb
<div id="task_modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Task</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with url: tasks_path, id: 'task_form', method: :post do |form| %>
        <div class="modal-body">
          <div class="form-group">
            <%= form.text_field :description, id: "task_description", name: "task[description]", class: "form-control", placeholder: "Description", required: true %>
          </div>
          <div id="sub_tasks_container" class="pt-2">
          </div>
          <button type="button" id="add_sub_task" class="btn btn-info btn-sm mt-3">Add Sub-task</button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= form.submit "Save changes", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div id="sub_task_input" hidden>
  <div class="input-group m-2">
    <div class="input-group-prepend">
      <span>|_____</span>
    </div>
    <input type="text" name="task[sub_tasks_attributes][][description]" class="form-control ml-4" placeholder="Sub-task">
  </div>
</div>
<%= hidden_field_tag :_method, 'patch', id: "update_field" %>

app/views/tasks/partials/_task_item.html.erb
<div class="card-header" id="heading_<%= task.id %>">
  <h2 class="mb-0">
    <div class="row d-flex justify-content-between">
      <span class="p-1 w-75">
        <div class="row d-flex justify-content-between">
          <span class="h6 ml-3 text-truncate w-50" title="<%= task.description %>">
            <%= task.description %>
          </span>
          <% if task.status.last.display == "Done" %>
            <i class="fa fa-check text-success" aria-hidden="true"></i>
          <% end %>
        </div>
      </span>
      <div class="row mr-3">
        <%= link_to "#", remote: true, class: "edit_task", data: {id: task.id,
                                            description: task.description} do %>
          <i class="fa fa-edit text-muted m-1 small"></i>
        <% end %>
        <% if !task.sub_tasks.empty? %>
          <%= link_to '#', remote: true do %>
            <i class="fa fa-caret-down text-muted m-1 small" data-toggle="collapse"
                                      data-target="#collapse_<%= task.id %>"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </h2>
</div>
<div id="collapse_<%= task.id %>" class="collapse" aria-labelledby="heading_<%= task.id %>"
                                                            data-parent="#tasks_accordion">
  <div class="card-body">
    <% if !sub_tasks.empty? %>
      <span class="h6 text-muted">Sub Tasks</span>
      <hr>
        <div class="row">
          <% sub_tasks.each do |sub_task| %>
            <div class="col-12">
              <div class="d-flex justify-content-between">
                <div class="m-1">
                  <%= sub_task.description %>
                </div>
                <div class="text-center">
                  <% if sub_task.status.last.display == "Pending" %>                  
                      <button class="btn btn-sm btn-outline-warning mr-3"><%= sub_task.status.last.display %></button>
                      <%= link_to next_status_sub_task_path(sub_task), method: :next_status,
                                    data: {id: task.id, description: task.description} do %>
                        <i class="fa fa-arrow-right text-muted m-1 small"></i>
                      <% end %>
                      <%= link_to sub_task_path(sub_task), method: :delete,
                                    data: {id: task.id, description: task.description} do %>
                        <i class="fa fa-trash text-muted m-1 small"></i>
                      <% end %>
                  <% elsif sub_task.status.last.display == "Ongoing" %>

                      <button class="btn btn-sm btn-outline-info mr-3"><%= sub_task.status.last.display %></button>
                      <%= link_to revert_status_sub_task_path(sub_task), method: :revert_status,
                                    data: {id: task.id, description: task.description} do %>
                        <i class="fa fa-arrow-left text-muted m-1 small"></i>
                      <% end %>
                      <%= link_to next_status_sub_task_path(sub_task), method: :next_status,
                                    data: {id: task.id, description: task.description} do %>
                        <i class="fa fa-arrow-right text-muted m-1 small"></i>
                      <% end %>
                  <% else %>
                      <button class="btn btn-sm btn-outline-success mr-3"><%= sub_task.status.last.display %></button>
                      <%= link_to revert_status_sub_task_path(sub_task), method: :revert_status,
                                    data: {id: task.id, description: task.description} do %>
                        <i class="fa fa-arrow-left text-muted m-1 small"></i>
                      <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
    <% end %>
  </div>
</div>